In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('/content/covid_toy.csv')

In [4]:
df.sample(5) #as we can see that gender,city is a nominal and cough is ordinal and on has_covid label encoder

age  gender  fever   cough       city has_covid
44   20    Male  102.0  Strong      Delhi        No
35   82  Female  102.0  Strong  Bangalore        No
99   10  Female   98.0  Strong    Kolkata       Yes
65   69  Female  102.0    Mild  Bangalore        No
58   23    Male   98.0  Strong     Mumbai       Yes

In [5]:
df.isnull().sum() #as we can see that there is missing values in fever column

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

#1.Aam Jindagi (converting the columns one by one)

In [19]:
# filling the missing values of the data with the mean of the data by using simple imputer
si= SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [8]:
#Ordinal Encoding on cough
oe= OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])
x_test_cough=oe.transform(x_test[['cough']])
x_train_cough.shape

(80, 1)

In [20]:
#one hot encoding -> gender,city
ohe= OneHotEncoder(drop='first',sparse=False) #we use sparse as we are passing two of the columns and drop ='first' as machine understood the default value so it helps to reduce the columns
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city=ohe.transform(x_test[['gender','city']])
x_test_gender_city.shape

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(20, 4)

In [21]:
#now accesing the age column
x_train_age=x_train.drop(columns=['gender','city','fever']).values
x_test_age=x_test.drop(columns=['gender','city','fever']).values
x_test_age.shape


(20, 2)

In [23]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1) #total 7 columns will be formed but cough creates a numpy wit its own string column
x_train_transformed=np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)
x_train_transformed

array([[48, 'Mild', 103.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [6, 'Mild', 104.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [27, 'Mild', 100.0, 1.0, 1.0, 0.0, 0.0, 0.0],
       [47, 'Strong', 101.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [12, 'Strong', 98.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [27, 'Mild', 100.0, 1.0, 0.0, 1.0, 0.0, 0.0],
       [59, 'Strong', 99.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [5, 'Strong', 98.0, 0.0, 0.0, 0.0, 1.0, 1.0],
       [10, 'Strong', 98.0, 0.0, 0.0, 1.0, 0.0, 1.0],
       [51, 'Strong', 101.0, 0.0, 0.0, 1.0, 0.0, 1.0],
       [69, 'Mild', 102.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [25, 'Mild', 104.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [65, 'Mild', 98.0, 0.0, 0.0, 0.0, 1.0, 0.0],
       [82, 'Strong', 102.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [46, 'Strong', 103.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [80, 'Mild', 98.0, 0.0, 1.0, 0.0, 0.0, 0.0],
       [83, 'Mild', 103.0, 1.0, 0.0, 1.0, 0.0, 0.0],
       [50, 'Mild', 103.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [15, 'Mild', 101.0, 1.0, 1.0, 0

In [12]:
final=pd.DataFrame(x_train_transformed)#we have converted the numpy into the dataframe to drop the mild column

In [13]:
final=final.drop(columns=[1])

In [14]:
final

0      2    3    4    5    6    7
0   48  103.0  0.0  0.0  1.0  0.0  0.0
1    6  104.0  0.0  0.0  1.0  0.0  0.0
2   27  100.0  1.0  1.0  0.0  0.0  0.0
3   47  101.0  1.0  0.0  0.0  0.0  1.0
4   12   98.0  1.0  0.0  0.0  0.0  1.0
5   27  100.0  1.0  0.0  1.0  0.0  0.0
6   59   99.0  0.0  1.0  0.0  0.0  1.0
7    5   98.0  0.0  0.0  0.0  1.0  1.0
8   10   98.0  0.0  0.0  1.0  0.0  1.0
9   51  101.0  0.0  0.0  1.0  0.0  1.0
10  69  102.0  0.0  0.0  0.0  0.0  0.0
11  25  104.0  1.0  0.0  0.0  0.0  0.0
12  65   98.0  0.0  0.0  0.0  1.0  0.0
13  82  102.0  0.0  0.0  0.0  0.0  1.0
14  46  103.0  1.0  0.0  0.0  0.0  1.0
15  80   98.0  0.0  1.0  0.0  0.0  0.0
16  83  103.0  1.0  0.0  1.0  0.0  0.0
17  50  103.0  0.0  0.0  1.0  0.0  0.0
18  15  101.0  1.0  1.0  0.0  0.0  0.0
19  64   98.0  0.0  0.0  0.0  0.0  0.0

In [15]:
final=final.values #converting the dataframe into the numpy

In [16]:
final

array([[48, 103.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [6, 104.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [27, 100.0, 1.0, 1.0, 0.0, 0.0, 0.0],
       [47, 101.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [12, 98.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [27, 100.0, 1.0, 0.0, 1.0, 0.0, 0.0],
       [59, 99.0, 0.0, 1.0, 0.0, 0.0, 1.0],
       [5, 98.0, 0.0, 0.0, 0.0, 1.0, 1.0],
       [10, 98.0, 0.0, 0.0, 1.0, 0.0, 1.0],
       [51, 101.0, 0.0, 0.0, 1.0, 0.0, 1.0],
       [69, 102.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [25, 104.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [65, 98.0, 0.0, 0.0, 0.0, 1.0, 0.0],
       [82, 102.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [46, 103.0, 1.0, 0.0, 0.0, 0.0, 1.0],
       [80, 98.0, 0.0, 1.0, 0.0, 0.0, 0.0],
       [83, 103.0, 1.0, 0.0, 1.0, 0.0, 0.0],
       [50, 103.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [15, 101.0, 1.0, 1.0, 0.0, 0.0, 0.0],
       [64, 98.0, 0.0, 0.0, 0.0, 0.0, 0.0]], dtype=object)

# Column transfer for doing the above task easily

In [17]:
from sklearn.compose import ColumnTransformer
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first',sparse=False),['gender','city'])
],remainder='passthrough')

In [18]:
transformer.fit_transform(x_train)
transformer.transform(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [ 99.,   1.,   0.,   1.,   0.,   0.,  59.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [103.,   0.,   1.,   0.,   1.,   0.,  83.],
       [103.,   0.,   0.,   0.,   1.,   0.,  50.],
       [101.,   0.,   1.,   1.,   0.,   0.,  15.],
       [ 98.,   0.,   0.,   0.,